FROM jdvelasq/python3:colab

# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.183.0/containers/python-3/.devcontainer/base.Dockerfile

# [Choice] Python version: 3, 3.9, 3.8, 3.7, 3.6
# ARG VARIANT="3.9"
# FROM mcr.microsoft.com/vscode/devcontainers/python:0-${VARIANT}

# [Option] Install Node.js
# ARG INSTALL_NODE="true"
# ARG NODE_VERSION="lts/*"
# RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "umask 0002 && . /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# RUN pip3 --disable-pip-version-check --no-cache-dir install \
#     bandit \
#     black \
#     flake8 \
#     isort \
#     jedi \
#     mypy \
#     nose \
#     poetry \
#     prospector \
#     pycodestyle \
#     pylama \
#     pylint \
#     pytest \
#     rope \
#     yapf    



# RUN apt-get update \
#     && apt-get -yq --no-install-recommends install  pandoc  make \
#     && apt-get clean \
#     && apt-get autoremove -yq \
#     && rm -rf /var/lib/apt/lists/* 

# RUN python3 -m pip install \
#     altair \
#     flask  \
#     gensim \
#     graphviz \
#     h5py \
#     ipykernel \
#     ipywidgets \
#     isort \
#     Jinja2 \
#     keras-tuner \
#     matplotlib \
#     nbsphinx \
#     networkx \
#     nltk \
#     numpy \
#     pandas \
#     pandas-datareader \
#     pandas-gbq \
#     pandas-profiling \
#     progressbar2 \
#     pydotplus  \
#     pygments \
#     pytest \
#     pyyaml \
#     scikit-learn \
#     scipy \
#     seaborn \
#     sklearn-pandas \
#     snowballstemmer \
#     spacy \
#     sphinx_copybutton \
#     sphinx-rtd-theme \ 
#     sphinx==4.0.3 \
#     SQLAlchemy \
#     statsmodels \
#     tensorboard \
#     tensorflow \
#     tensorflow_io \
#     tensorflow-addons \
#     tensorflow-datasets \
#     tensorflow-estimator \
#     tensorflow-hub \
#     tensorflow-text \
#     textblob \
#     widgetsnbextension \
#     wordcloud

# RUN pip install -q git+https://github.com/tensorflow/docs

# RUN pip install -q git+https://github.com/tensorflow/examples.git

# RUN apt update \
#     && apt -yq --no-install-recommends install  graphviz \
#     && apt clean \
#     && apt autoremove -yq \
#     && rm -rf /var/lib/apt/lists/* 
