
Vagrant.configure("2") do |config|
  
    config.vm.box = "ubuntu/bionic64"
    
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -yq \
        build-essential \
        tree \
        python-dev \
        python3-minimal \
        python3-pip \
        python3-dev \       
        python3-venv
      sudo apt-get update
      pip3 install --upgrade pip 
      pip3 install pandas matplotlib scikit-learn flask
    SHELL

    config.vm.network :forwarded_port, guest: 5000, host: 1234, host_ip: "127.0.0.1"
    
end
